# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.1.x
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.x


- script: dotnet test XUnitTestProject --configuration Release --logger "trx;LogFileName=XUnitTestProject.trx" --results-directory _.testsOutput /property:CollectCoverage=True /property:CoverletOutputFormat=opencover
  displayName: 'dotnet test'


- script: dotnet tool install Nuke.GlobalTool --global
  displayName: Nuke install
- script: nuke
  displayName: 'nuke test'


  